/***************************************************************
 * Name:      AboutBoxDialog.h
 * Purpose:   Code for About Box
 * Author:    Faro Salvatore (info@mtx-electronics.com)
 * Created:   2009-09-14
 * Copyright: MTX Electronics (www.mtx-electronics.com)
 ***************************************************************
 *
 * This file is part of CrossTuner Studio.
 *
 *    CrossTuner Studio is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    CrossTuner Studio is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with the CrossTuner Studio Code.  
 *    If not, see <http://www.gnu.org/licenses/>.
 *
 ***************************************************************/
 
// Generated by DialogBlocks (unregistered), 24/01/2009 17:36:37

#ifndef _AboutBoxDialog_H_
#define _AboutBoxDialog_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/gbsizer.h"
#include "wx/statline.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define SYMBOL_AboutBoxDialog_STYLE wxCAPTION|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_AboutBoxDialog_TITLE _("About ")
#define SYMBOL_AboutBoxDialog_IDNAME ID_AboutBoxDialog
#define SYMBOL_AboutBoxDialog_SIZE wxSize(400, 300)
#define SYMBOL_AboutBoxDialog_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * AboutBoxDialog class declaration
 */

class AboutBoxDialog: public wxDialog
{
    DECLARE_DYNAMIC_CLASS( AboutBoxDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    AboutBoxDialog();
    AboutBoxDialog( wxWindow* parent,
		wxWindowID id = SYMBOL_AboutBoxDialog_IDNAME,
		const wxString& caption = SYMBOL_AboutBoxDialog_TITLE,
		const wxPoint& pos = SYMBOL_AboutBoxDialog_POSITION,
		const wxSize& size = SYMBOL_AboutBoxDialog_SIZE,
		long style = SYMBOL_AboutBoxDialog_STYLE );

    /// Destructor
    ~AboutBoxDialog();

    /// Initialises member variables
    void Init();

    /// Creation
    bool Create( wxWindow* parent,
		wxWindowID id = SYMBOL_AboutBoxDialog_IDNAME,
		const wxString& caption = SYMBOL_AboutBoxDialog_TITLE,
		const wxPoint& pos = SYMBOL_AboutBoxDialog_POSITION,
		const wxSize& size = SYMBOL_AboutBoxDialog_SIZE,
		long style = SYMBOL_AboutBoxDialog_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin AboutBoxDialog event handler declarations

////@end AboutBoxDialog event handler declarations

////@begin AboutBoxDialog member function declarations

    wxString GetAppName() const { return m_AppName ; }
    void SetAppName(wxString value) { m_AppName = value ; }

    wxString GetVersion() const { return m_Version ; }
    void SetVersion(wxString value) { m_Version = value ; }

    wxString GetCopyright() const { return m_Copyright ; }
    void SetCopyright(wxString value) { m_Copyright = value ; }

    wxString GetCustomBuildInfo() const { return m_CustomBuildInfo ; }
    void SetCustomBuildInfo(wxString value) { m_CustomBuildInfo = value ; }

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end AboutBoxDialog member function declarations

    //helper functions
    enum wxBuildInfoFormat
    {
        wxBUILDINFO_SHORT,
        wxBUILDINFO_LONG
    };

    static wxString GetBuildInfo(wxBuildInfoFormat format);

    void SetHeaderBitmap(const wxBitmap & value);
    void ApplyInfo();

private:
////@begin AboutBoxDialog member variables
    wxPanel* m_ContentPanel;
    wxStaticBitmap* m_HeaderStaticBitmap;
    wxStaticText* m_AppNameStaticText;
    wxStaticText* m_CopyrightStaticText;
    wxStaticText* m_VersionStaticText;
    wxStaticText* m_BuildInfoStaticText;
    wxString m_AppName;
    wxString m_Version;
    wxString m_Copyright;
    wxString m_CustomBuildInfo;
    /// Control identifiers
    enum {
        ID_AboutBoxDialog = 10000,
        ID_ContentPanel = 10001
    };
////@end AboutBoxDialog member variables
};

#endif
    // _AboutBoxDialog_H_
